name: Integration tests

on: [pull_request]

env:
  CI: true
  WALLET_ENVIRONMENT: testing

jobs:
  directories:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }}
    steps:
      - uses: actions/checkout@v2
      - id: set-dirs
        working-directory: ./tests-legacy/integration
        run: echo "::set-output name=dir::$( ls -d */ | xargs -0 | sed 's/\///' | jq -R -s -c 'split("\n")[:-2]')"

  test-integration:
    runs-on: ubuntu-latest
    needs: [directories]
    strategy:
      matrix:
        dir: ${{ fromJson(needs.directories.outputs.dir) }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - run: echo ${{ fromJson(needs.directories.outputs.dir) }}
      - run: echo ${{ matrix.dir }}

      - uses: actions/cache@v2
        name: Cache node_modules
        id: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}

      - uses: actions/cache@v2
        name: Cache playwright
        id: cache-playwright-browsers
        with:
          path: '~/.cache/ms-playwright'
          key: ${{ runner.os }}-playwright-browser

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install packages
        uses: ./.github/actions/provision
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Install Playwright dependencies
        run: npx playwright install

      - name: Build assets
        run: yarn build:test

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Run tests
        run: |
          xvfb-run --auto-servernum -- \
            yarn jest \
              --config=./jest.integration.config.js \
              --detectOpenHandles \
              --forceExit \
              --testPathPattern=./tests-legacy/integration/${{ matrix.dir }}/*

      - name: Upload traces
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: traces-${{ matrix.dir }}-${{ steps.date.outputs.date }}
          path: '**/**.trace.zip'
